version: '3.8'

services:
  mmemory:
    build: .
    container_name: mmemory-bot
    restart: unless-stopped
    environment:
      # Telegram Bot Token (必须设置)
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

      # 数据库配置
      - DATABASE_PATH=/app/data/mmemory.db

      # 应用配置
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - LOG_FORMAT=json

      # 时区设置
      - TZ=Asia/Shanghai

      # AI Configuration (OpenAI)
      - MMEMORY_AI_ENABLED=${MMEMORY_AI_ENABLED:-true}
      - MMEMORY_AI_OPENAI_API_KEY=${MMEMORY_AI_OPENAI_API_KEY}
      - MMEMORY_AI_OPENAI_BASE_URL=${MMEMORY_AI_OPENAI_BASE_URL:-https://api.openai.com/v1}
      - MMEMORY_AI_OPENAI_PRIMARY_MODEL=${MMEMORY_AI_OPENAI_PRIMARY_MODEL:-gpt-4o-mini}
      - MMEMORY_AI_OPENAI_BACKUP_MODEL=${MMEMORY_AI_OPENAI_BACKUP_MODEL:-gpt-3.5-turbo}
      - MMEMORY_AI_OPENAI_TEMPERATURE=${MMEMORY_AI_OPENAI_TEMPERATURE:-0.1}
      - MMEMORY_AI_OPENAI_MAX_TOKENS=${MMEMORY_AI_OPENAI_MAX_TOKENS:-1000}
      - MMEMORY_AI_OPENAI_TIMEOUT=${MMEMORY_AI_OPENAI_TIMEOUT:-30s}
      - MMEMORY_AI_OPENAI_MAX_RETRIES=${MMEMORY_AI_OPENAI_MAX_RETRIES:-3}
    volumes:
      # 持久化数据库文件
      - ./data:/app/data
      
      # 可选：挂载自定义配置文件
      # - ./configs/config.yaml:/app/configs/config.yaml:ro
    ports:
      # 应用端口
      - "8080:8080"
      # 监控端口
      - "9090:9090"
    networks:
      - mmemory-network
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "mmemory", "|", "grep", "-v", "grep"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mmemory-network:
    driver: bridge

# 如果需要使用外部PostgreSQL数据库（可选）
# services:
#   postgres:
#     image: postgres:15-alpine
#     container_name: mmemory-db
#     restart: unless-stopped
#     environment:
#       - POSTGRES_DB=mmemory
#       - POSTGRES_USER=mmemory
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - mmemory-network
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U mmemory"]
#       interval: 30s
#       timeout: 10s
#       retries: 5

# volumes:
#   postgres_data: