groups:
  - name: mmemory.alerts
    rules:
      # 系统可用性告警
      - alert: MMemoryDown
        expr: up{job="mmemory"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "MMemory服务不可用"
          description: "MMemory服务已停止运行超过1分钟"

      # 错误率告警
      - alert: MMemoryHighErrorRate
        expr: rate(mmemory_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "MMemory错误率过高"
          description: "过去5分钟错误率超过10%"

      # 响应时间告警
      - alert: MMemoryHighResponseTime
        expr: histogram_quantile(0.95, rate(mmemory_response_duration_seconds_bucket[5m])) > 2
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "MMemory响应时间过长"
          description: "95%分位响应时间超过2秒"

      # 数据库连接告警
      - alert: MMemoryDatabaseErrors
        expr: rate(mmemory_database_queries_total{status="failed"}[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "MMemory数据库错误率过高"
          description: "数据库查询失败率超过5%"

      # 调度器告警
      - alert: MMemorySchedulerDown
        expr: mmemory_scheduler_jobs_total == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "MMemory调度器无任务"
          description: "调度器中没有活跃的提醒任务"

      # 提醒积压告警
      - alert: MMemoryReminderBacklog
        expr: mmemory_reminders_total{status="pending"} > 100
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "MMemory提醒积压过多"
          description: "待处理提醒数量超过100个"

      # 通知发送失败告警
      - alert: MMemoryNotificationFailures
        expr: rate(mmemory_notifications_total{status="failed"}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "MMemory通知发送失败率过高"
          description: "通知发送失败率超过10%"

      # Telegram API状态告警
      - alert: TelegramAPIUnavailable
        expr: probe_success{job="telegram_api"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Telegram API不可用"
          description: "Telegram Bot API服务不可用"

      # 内存使用告警
      - alert: MMemoryHighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "MMemory内存使用率过高"
          description: "内存使用率超过90%"

      # CPU使用告警
      - alert: MMemoryHighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "MMemory CPU使用率过高"
          description: "CPU使用率超过80%"

      # 磁盘空间告警
      - alert: MMemoryLowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "MMemory磁盘空间不足"
          description: "磁盘可用空间少于10%"