# MMemory 配置文件示例
# 这是一个完整的配置文件示例，展示了所有可用的配置选项
# 你可以根据实际需求进行修改

# Telegram Bot 配置
bot:
  # Bot Token - 必需，从 @BotFather 获取
  token: "your_telegram_bot_token_here"
  
  # 调试模式 - 可选，默认 false
  debug: false
  
  # Webhook 配置 - 可选，默认使用轮询模式
  webhook:
    enabled: false
    url: "https://your-domain.com/webhook"
    port: 8443

# 数据库配置
database:
  # 数据库驱动 - 可选，默认 sqlite3，支持: sqlite3, mysql, postgres
  driver: "sqlite3"
  
  # 数据库连接字符串 - 必需
  # SQLite: "./data/mmemory.db"
  # MySQL: "user:password@tcp(localhost:3306)/mmemory?charset=utf8mb4&parseTime=True&loc=Local"
  # PostgreSQL: "host=localhost user=mmemory password=password dbname=mmemory port=5432 sslmode=disable TimeZone=Asia/Shanghai"
  dsn: "./data/mmemory.db"
  
  # 最大连接数 - 可选，默认 25
  max_open_conns: 25
  
  # 最大空闲连接数 - 可选，默认 10
  max_idle_conns: 10

# 服务器配置
server:
  # 服务器端口 - 可选，默认 8080
  port: "8080"
  
  # 服务器主机地址 - 可选，默认 "0.0.0.0"
  host: "0.0.0.0"

# 调度器配置
scheduler:
  # 时区 - 可选，默认 "Asia/Shanghai"
  timezone: "Asia/Shanghai"
  
  # 最大工作线程数 - 可选，默认 10
  max_workers: 10

# 日志配置
logging:
  # 日志级别 - 可选，默认 "info"，支持: debug, info, warn, error
  level: "info"
  
  # 日志格式 - 可选，默认 "json"，支持: json, text
  format: "json"
  
  # 日志输出方式 - 可选，默认 "stdout"，支持: stdout, file, both
  output: "stdout"
  
  # 日志文件路径 - 可选，默认 "./data/mmemory.log"
  # 仅在 output 为 "file" 或 "both" 时有效
  file_path: "./data/mmemory.log"

# 应用配置
app:
  # 应用名称 - 可选，默认 "MMemory"
  name: "MMemory"
  
  # 应用版本 - 可选，默认 "v0.0.1"
  version: "v0.0.1"
  
  # 应用环境 - 可选，默认 "development"，支持: development, testing, staging, production
  environment: "development"

# 监控配置
monitoring:
  # 是否启用监控 - 可选，默认 true
  enabled: true
  
  # 监控端口 - 可选，默认 9090
  port: 9090
  
  # 监控路径 - 可选，默认 "/metrics"
  path: "/metrics"