global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mmemory-monitor'

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 加载告警规则
rule_files:
  - "alerts/*.yml"

# 抓取目标配置
scrape_configs:
  # MMemory应用监控
  - job_name: 'mmemory'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: '/metrics'
    
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    
  # 系统监控 (需要node_exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s
    
  # Telegram Bot API监控 (需要blackbox_exporter)
  - job_name: 'telegram_api'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.telegram.org
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115